Dev lesson2
11albina19/TestGuru pull request #1
Opened 2024-01-14 21:07 UTC by 11albina19

Ветка к уроку 2

2024-01-15 05:39 UTC, VidgarVii requested changes

2024-01-15 05:39 UTC, VidgarVii commented on app/controllers/others_controller.rb
> +class OthersController < ApplicationController
как указано в скринкасте, `html` файлы целиком статические будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2024-01-15 05:39 UTC, VidgarVii commented on app/views/others/about.html.erb
> +<p>Создано при обучении в онлайн-школе <a href="<%= @thinknetica_link %>" target="_blank">thinknetica</a></p>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-01-15 05:39 UTC, VidgarVii commented on config/initializers/version.rb
> +  def self.version
метод тут лишний. Чтобы обратиться к константе метод не нужен

2024-01-15 05:39 UTC, VidgarVii commented on config/initializers/version.rb
> +module TestGuruVersion
уже есть модуль Testguru. Новый модуль содздавать нет смысла.
А так как надо задать версию для приложения, то и класс для этого уже есть Application 
Посмотри файл config/application.rb

2024-01-15 05:39 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2024-01-15 05:39 UTC, VidgarVii commented on README.md
почти верно. 
список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

 Лишнее нужно будет убрать

2024-01-15 17:38 UTC, 11albina19 commented on app/controllers/others_controller.rb
> +class OthersController < ApplicationController
А где можно увидеть этот скриншот? Здесь куда-то нужно нажать?

2024-01-16 04:21 UTC, VidgarVii commented on config/application.rb
> +    VERSION = '0.1.0'
по ТЗ 
Добавьте Initializer с версией приложения (используйте [semver.org](https://semver.org/)). Для этого добавьте файл version.rb с нужным кодом в config/initilizers/

2024-01-16 04:21 UTC, VidgarVii commented on public/about.html
> +<html lang="en">
не стыковка с языком. Ни же то текст на русском. А код говорит, что английский

2024-01-16 13:44 UTC, VidgarVii commented on config/initializers/version.rb
> +end
https://github.com/11albina19/TestGuru/pull/1#discussion_r1451943974

2024-01-16 13:44 UTC, VidgarVii commented on config/initializers/version.rb
> +    VERSION = '0.1.0'
"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми

2024-01-18 17:11 UTC, merged