dev lesson10
11albina19/TestGuru pull request #10
Opened 2024-12-02 00:51 UTC by 11albina19

Часть 10

2024-12-03 11:01 UTC, VidgarVii requested changes

2024-12-03 11:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:user_id] = current_user&.id
логин происходит не тут
cookies[:user_id] не используется. Сохранять нет смысла

2024-12-03 11:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
cookies[:email] не используется. Нет смысла его сохранять

2024-12-03 11:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies.delete(:remember_token)
от куда взялся remember_token?)

2024-12-03 11:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    session.delete(:user_id)
https://apidock.com/rails/ActionController/Base/reset_session

2024-12-03 11:01 UTC, VidgarVii commented on db/migrate/20241201230158_rename_mail_to_email_in_users.rb
> +class RenameMailToEmailInUsers < ActiveRecord::Migration[7.0]
кол-во мираций для одной таблицы стоит уменьшить в этом ПР до одной

2024-12-03 11:01 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#destroy'
Это лучше сделать HTTP-методом DELETE, чтоб соблюдалась семантика REST. Ресурсы удаляют только методом DELETE

2024-12-06 15:07 UTC, 11albina19 commented on app/controllers/application_controller.rb
> +    cookies.delete(:remember_token)
Упс... Поняла, убрала. Вообще вот отсюда: https://www.softcover.io/read/db8803f7/ruby_on_rails_tutorial_3rd_edition_russian/log_in_log_out#code-log_out_with_forget

2024-12-06 15:17 UTC, VidgarVii requested changes

2024-12-06 15:17 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies.delete(:return_to)
cookies.delete(:return_to)
это можно сделать сразу на 12 строке. Посмотри что возвращает метод delete

2024-12-06 15:17 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    reset_session if logged_in?
тут в любом случаи надо делать reset_session

2024-12-06 15:17 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +  def delete
соглансо соглашению экшен должен называться destroy

2024-12-06 15:17 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#delete'
прошлое замечания было понятно не верно. Экшен должен быть destroy
. А вот метод запроса должен быть delete, а не get
Стоит пересмотреть урок по REST

2024-12-06 15:17 UTC, VidgarVii commented on db/migrate/20241206145543_users_table_changed.rb
> +  end
миграция не является откатываемой. Надо указать типы полей

2024-12-12 14:52 UTC, merged